run:
  go: '1.22'
linters:
  enable:
    - govet
    - typecheck
    - unused
    - gofmt
    - whitespace
    - gosimple
    - nilerr
    - goimports
    - staticcheck
    - ineffassign
    - errcheck
  disable:
    - depguard
